rearrange:
  dataset_name: # the name of dataset
    choices: ['FaceForensics++', 'DeepFakeDetection', 'Celeb-DF-v1', 'Celeb-DF-v2','DFDCP', 'DFDC', 'DeeperForensics-1.0','UADFV','FaceShifter']
    # default: 'A_data'
    default: 'DATASET_YOU_SPECIFY'
    # default: 'web'
    # default: 'web2'
    # default: 'whichfaceisreal'
  dataset_root_path: # the root path to the dataset
    type: str
    default: './datasets'
  output_file_path: # the json path to the dataset
    type: str
    default: './preprocessing/dataset_json'
  comp: # the compression level of videos, only in the dataset of FaceForensics++.
    choices: ['raw', 'c23', 'c40']
    default: 'c23'
  perturbation: # Extensive real-world perturbations are applied to DeeperForensics-1.0 dataset
    choices: ['end_to_end','end_to_end_level_1','end_to_end_level_2','end_to_end_level_3','end_to_end_level_4',
              'end_to_end_level_5','end_to_end_mix_2_distortions','end_to_end_mix_3_distortions',
              'end_to_end_mix_4_distortions','end_to_end_random_level','reenact_postprocess']
    default: 'end_to_end'