mode: train
lmdb: False
dry_run: false
rgb_dir: './datasets/rgb'
lmdb_dir:  './datasets/lmdb'
dataset_json_folder: './preprocessing/dataset_json'
SWA: False
save_avg: True
log_dir: ./logs/training/
# label settings
label_dict:
  # DFD
  DFD_fake: 1
  DFD_real: 0
  # FF++ + FaceShifter(FF-real+FF-FH)
  FF-SH: 1
  FF-F2F: 1
  FF-DF: 1
  FF-FS: 1
  FF-NT: 1
  FF-FH: 1
  FF-real: 0
  # CelebDF
  CelebDFv1_real: 0
  CelebDFv1_fake: 1
  CelebDFv2_real: 0
  CelebDFv2_fake: 1
  # DFDCP
  DFDCP_Real: 0
  DFDCP_FakeA: 1
  DFDCP_FakeB: 1
  # DFDC
  DFDC_Fake: 1
  DFDC_Real: 0
  # DeeperForensics-1.0
  DF_fake: 1
  DF_real: 0
  # UADFV
  UADFV_Fake: 1
  UADFV_Real: 0
  # Roop
  roop_Real: 0
  roop_Fake: 1
  # A_data
  A_data_Fake: 1
  A_data_Real: 0
  # B_data
  B_data_Fake: 1
  B_data_Real: 0
  # phase
  phase_Fake: 1
  phase_Real: 0
  # debug_train
  debug_train_Fake: 1
  debug_train_Real: 0
  # debug_test
  debug_test_Fake: 1
  debug_test_Real: 0
  # my_data
  my_data_Fake: 1
  my_data_Real: 0
  # whichfacecisreal
  whichfaceisreal_Fake: 1
  whichfaceisreal_Real: 0
  # web
  web_Fake: 1
  web_Real: 0
  # web2
  web2_Fake: 1
  web2_Real: 0