# PREPROCESSING:
#   DATASET: Celeb-DFv2
#   COMPRESSION: c0
#   SPLIT: test
#   ROOT: /data/deepfake_cluster/datasets_df/Celeb-DFv2/
#   # FAKETYPE: [Deepfakes, Face2Face, FaceSwap, NeuralTextures]
#   FAKETYPE: [YouTube-real]
#   IMAGE_SUFFIX: png
#   DATA_TYPE: frames
#   LABEL: [real]
#   facial_lm_pretrained: pretrained/shape_predictor_81_face_landmarks.dat
#   N_LANDMARKS: 81
#   SAMPLING:
#     ACTIVE: False
#     NUMBERS: 8
#   DEBUG: False

PREPROCESSING:
  DATASET: FF++
  COMPRESSION: c0
  SPLIT: val
  ROOT: ./data/FaceForensics++/c0/
  FAKETYPE: [original] # [Deepfakes, Face2Face, FaceSwap, NeuralTextures]
  IMAGE_SUFFIX: png
  DATA_TYPE: frames
  LABEL: [real]
  facial_lm_pretrained: pretrained/shape_predictor_81_face_landmarks/shape_predictor_81_face_landmarks.dat
  N_LANDMARKS: 81
  SAMPLING:
    ACTIVE: False
    NUMBERS: 8
  DEBUG: False